### ISSUE TITLE
[ENHANCEMENT] Implement new Navbar design 

### ISSUE THREAD

**Issue by furkanmutlu** [MutluMinds/fullstack-image-app#63]
- We should use dropdown for choosing dropdown.
- screen shot of new design can be found below:

![image](https://user-images.githubusercontent.com/45897337/209852605-256625f0-79da-4379-b017-7110d9828638.png)

**Comment by AlfiyaSiddique** [comment]
Hello @furkanmutlu 

I think, we should add a background color to the above navbar design, Because without a background color when the navbar appears above the images, it looks like this:
<img width="946" alt="Screenshot 2023-01-04 220444" src="https://user-images.githubusercontent.com/86224794/210713189-5a09188c-4d39-4307-981e-7e1bf0459a3c.png">

But with the Background color, it looks better:
<img width="937" alt="Screenshot 2023-01-04 220617" src="https://user-images.githubusercontent.com/86224794/210713246-cbc284d0-e45b-4697-b578-f623caeb0793.png">

But because of the background color, the GitHub sticker is not visible:
<img width="961" alt="Screenshot 2023-01-05 114136" src="https://user-images.githubusercontent.com/86224794/210713741-49be2226-edb9-4df2-b028-981f277178a1.png">

My solution to this is, we can add another button on the left side of the navbar just like the scroll-up button for a link to this remote repository.

What do you think?

**Comment by furkanmutlu** [comment]
You have a great point!  What do you think about the new design below ?  If you think this is too big changes for what you have done already, you can go with your solution. And we can create ticket for new one later. 

<img width="766" alt="image" src="https://user-images.githubusercontent.com/45897337/210837964-c6c355dc-76f6-4c9e-9815-500bb44ee8d0.png">

**Comment by AlfiyaSiddique** [comment]
No problem, I'll do the changes for the new design👍🏻
