### ISSUE TITLE
[FEATURE] Add download button

### ISSUE THREAD

**Issue by furkanmutlu** [MutluMinds/fullstack-image-app#66]
![image](https://user-images.githubusercontent.com/45897337/209984987-5c22c5bd-1667-4fd4-b6e0-421fd144b169.png)

- Please add hover state as other buttons
- Clicking download button should download the image.
- Icon to use : `<FontAwesomeIcon icon="fas fa-file-download" />`
- https://fontawesome.com/v5/icons/file-download?s=solid&f=classic

**Comment by elyessAR** [comment]
@furkanmutlu what should we name the images downloaded from pixabay and unsplash since there is no title property in the retrieved image object from these two ?  right now it shows undefined.jpg when downloaded, giphy works with no issues because it has a title property.
![Screenshot_2](https://user-images.githubusercontent.com/49849558/210290948-96416630-dbde-474e-8541-362c3930f35b.png)

**Comment by furkanmutlu** [comment]
hmm, good point. I think we should handle it via our backend side first to ensure our api return an alt value. 
for giphy we can use `title`,
for pixabay, we could use either `tags` (first value or concatted str) or image id.
for unsplash  there is `alt_description`.
